version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: moviegraph-db
    restart: always
    environment:
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: moviepass
      POSTGRES_DB: moviedb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - moviegraph-net

  backend:
    build: ./back
    container_name: moviegraph-back
    restart: always
    env_file:
      - ./back/.env
    depends_on:
      - db
    ports:
      - "8001:8000"
    networks:
      - moviegraph-net

  db-init:
    build:
      context: ./back
      dockerfile: Dockerfile.init
    depends_on:
      - db
    command: ["python", "resources/create_tables.py"]
    networks:
      - moviegraph-net

  frontend:
    build: ./front
    container_name: moviegraph-front
    restart: always
    ports:
      - "3001:80"
    networks:
      - moviegraph-net

volumes:
  db_data:

networks:
  moviegraph-net:
