version: '3.8'

services:
  neo4j:
    image: neo4j:4.4.26
    container_name: moviegraph-neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_dbms_connector_bolt_advertised__address: "neo4j:7687"
      NEO4J_dbms_connector_http_advertised__address: "neo4j:7474"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data
    networks:
      - moviegraph-net
    env_file:
      - ./back/.env

  backend:
    build: ./back
    container_name: moviegraph-backend
    restart: always
    ports:
      - "9000:9000"
    env_file:
      - ./back/.env
    depends_on:
      - neo4j
    networks:
      - moviegraph-net

  frontend:
    image: nginx:alpine
    container_name: moviegraph-frontend
    volumes:
      - ./front/dist:/usr/share/nginx/html:ro
    ports:
      - "3100:80"
    networks:
      - moviegraph-net
    restart: always

volumes:
  neo4j_data:

networks:
  moviegraph-net:
