version: "3.8"

services:
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"       # HTTP
      - "81:81"       # Interfaz web
      - "443:443"     # HTTPS
    volumes:
      - nginx_data:/data
      - nginx_letsencrypt:/etc/letsencrypt

volumes:
  nginx_data:
  nginx_letsencrypt: