version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: moviegraph-db
    restart: always
    environment:
      POSTGRES_USER: movieuser
      POSTGRES_PASSWORD: moviepass
      POSTGRES_DB: moviedb
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - moviegraph-net

  backend:
    build: ./backend
    container_name: moviegraph-backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      - db
    ports:
      - "8001:8000"
    networks:
      - moviegraph-net

  frontend:
    build: ./frontend
    container_name: moviegraph-frontend
    restart: always
    ports:
      - "3001:80"
    networks:
      - moviegraph-net

volumes:
  db_data:

networks:
  moviegraph-net:
